### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jza34** [bytebutcher/bgl#1]
Hi, thanks for the well coded project. I was looking for something like "pet" but unfortunately I am not able to make bgl working!
I followed your instructions, I can use the `bgl` command under bash but no variable are exported at all

```
[lamy@pi ~]$ bgl list
[lamy@pi ~]$ bgl export name=value1
[lamy@pi ~]$ echo $name

[lamy@pi ~]$ bgl list
[lamy@pi ~]$ 
```

As you can see no variable "name" is stored.

Bash version: GNU bash, version 5.1.4(1)-release (aarch64-unknown-linux-gnu)
OS: Manjaro under RaspberryPi

Any idea?

**Comment by bytebutcher** [comment]
Hi @jza34,
thanks for reporting this issue. I made a fix and things should work as expected:
```
# remove old version
$ rm -rf ~/.bgl.bash
$ rm -rf ~/.bgl
# install latest version
$ bash <(curl -s https://raw.githubusercontent.com/bytebutcher/bgl/master/install)
# try it out
$ bgl export name=value1
$ echo $name
value1
```
